ZERO-48 : 마이히스토리 페이지 데이터 패칭
part4-6team/Coworkers pull request #15
Opened 2024-10-13 13:21 UTC by jangyonghan

# 작업분류
- [ ] 버그 수정
- [x] 신규 기능
- [ ] 리팩토링
- [ ] 기타

# 작업개요
- 마이 히스토리 페이지 데이터 패칭 -> api 연결 
- axios 인스턴스 생성
- dayjs 라이브러리 설치

# 작업 상세 내용
- 데이터 패칭 axios를 통해 하였고 lib폴더 안에 axios인스턴스 만들어놨습니다
- 목데이터를 통해서 페이지 확인했을때는 문제 없이 정상적으로 랜더링 되는것 확인 하였습니다.
- 날짜별로 완료된 할일들 묶어놓는 로직 작성하였습니다

- mock데이터를 통해서 랜더링한 페이지
<img width="1270" alt="데이터 패칭 pr 첨부사진" src="https://github.com/user-attachments/assets/18197d84-9b34-4774-b1b8-b258dc56d718">

# 리뷰 요구사항
- 로직에 잘못된 부분 있으면 피드백 부탁드립니다!!
- 아직 각 테스크별 수정하기 삭제하기는 못했는데 추후에 추가 PR올리도록 하겠습니다!!

# 연관된 Jira 티켓 번호
- ZERO-48 : https://fe08team4.atlassian.net/browse/ZERO-48?atlOrigin=eyJpIjoiNTQ0ZGE1MGZlYWI3NGFkYzg5YTU4ZTI3MTdmNTFlMzgiLCJwIjoiaiJ9

2024-10-13 20:54 UTC, choi-youngsun requested changes

2024-10-13 20:54 UTC, choi-youngsun commented on src/lib/axios.tsx
> +export default authAxiosInstance;
어 혹시 8-6 아닌가요?!

2024-10-14 01:14 UTC, jangyonghan commented on src/lib/axios.tsx
> +export default authAxiosInstance;
아...!ㅋㅋㅋㅋㅋ 감사합니다... 수정할게요

2024-10-14 01:35 UTC, hyeoksuJ commented on src/lib/axios.tsx
> +export default authAxiosInstance;
p3; 저희 각자 로컬에다가 .env.local 파일을 만들어서 사용하는게 어떨까요?
`NEXT_PUBLIC_API_URL = "https://fe-project-cowokers.vercel.app/8-6/"`

2024-10-14 01:42 UTC, jangyonghan commented on src/lib/axios.tsx
> +export default authAxiosInstance;
좋습니다!! 다음 PR에 추가해서 같이 올릴게요!!

2024-10-14 01:59 UTC, choi-youngsun approved these changes

2024-10-14 02:01 UTC, hyeoksuJ approved these changes

2024-10-14 02:12 UTC, merged