ZERO-155 : 닉네임 변경 글자 제한
part4-6team/Coworkers pull request #96
Opened 2024-11-02 09:09 UTC by jangyonghan

## 작업분류

- [x] 버그 수정
- [ ] 신규 기능
- [ ] 리팩토링
- [ ] 기타

## 작업개요

- 마이세팅 페이지 닉네임 글자 제한

## 작업 상세 내용

- 마이세팅 페이지 닉네임 글자 10글자 내외로 제한

---

## 스크린샷

![닉네임 변경 제한](https://github.com/user-attachments/assets/5e96756b-4a10-41be-a53f-2817a2ec8879)

---

## 리뷰 요구사항

_집중 리뷰 부분 작성_

## 연관된 Jira 티켓 번호
- ZEOR-155

2024-11-02 19:23 UTC, purplenib approved these changes

2024-11-03 00:59 UTC, hyeoksuJ approved these changes

2024-11-03 01:13 UTC, hyeoksuJ requested changes

2024-11-03 01:13 UTC, hyeoksuJ commented on src/components/mysetting/inputTask.tsx
> +          errorMessage="닉네임은 10글자 내외입니다."
p4; 라벨에 이름이라고 되어 있기도 하고 회원가입, 로그인도 이름으로 수정을 해서
에러메시지를 "이름은 10글자 이내로 작성해 주세요."로 통일 시키는 게 어떨까요?

2024-11-03 04:48 UTC, jangyonghan commented on src/components/mysetting/inputTask.tsx
> +          errorMessage="닉네임은 10글자 내외입니다."
넵! 좋습니다~!

2024-11-03 05:00 UTC, hyeoksuJ approved these changes

2024-11-03 05:01 UTC, merged